"""empty message

Revision ID: 212ea5e66da6
Revises: 
Create Date: 2017-12-11 05:45:55.370838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212ea5e66da6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
